using System;
using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Mutagen.Bethesda.Plugins.Exceptions;

namespace NPC_DeLeveler
{
    public class Program
    {
        private static Lazy<Settings> _lazySettings = null!;
        private static Settings Settings => _lazySettings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "NPC-Deleveler.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            int count = 0; // running change counter

            // iterate through all winning override npc records
            foreach (var npc in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                try // catch & enrich exceptions
                {
                    if (npc == null || npc.EditorID == null || (Settings.SkipPlayer && npc.EditorID.Equals("player", StringComparison.OrdinalIgnoreCase)))
                        continue;

                    var copy = Settings.ApplyTo(npc.DeepCopy(), out var changes);

                    if (changes > 0)
                    {
                        state.PatchMod.Npcs.Set(copy);
                        Console.WriteLine($"[{++count}]\tChanged {changes} level value{(changes > 1 ? "s" : "")} in {npc.EditorID}");
                    }
                }
                catch (Exception ex)
                {
                    throw RecordException.Enrich(ex, npc);
                }
            }

            // iterate through all leveled list entries
            foreach (var list in state.LoadOrder.PriorityOrder.LeveledNpc().WinningOverrides())
            {
                try // catch & enrich exceptions
                {
                    if (list == null || list.EditorID == null || list.Entries == null)
                        continue;

                    var copy = Settings.ApplyTo(list.DeepCopy(), out var changes);

                    if (changes > 0)
                    {
                        state.PatchMod.LeveledNpcs.Set(copy);
                        Console.WriteLine($"[{++count}]\tModified {changes} entr{(changes > 1 ? "ies" : "y")} in {list.EditorID}");
                    }
                }
                catch (Exception ex)
                {
                    throw RecordException.Enrich(ex, list);
                }
            }

            Console.WriteLine($"Process completed. Modified {count} records.");
        }
    }
}
